baseURL = "http://troubles.md/"
languageCode = "en-us"
title = "troubles.md"
theme = "one"
PygmentsCodeFences = true
PygmentsUseClasses = true

[params]
image = "floppies.png"

[blackfriday]
extension = ["footnotes"]
